# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Neco Kriel
masthead_title: "Neco Kriel"
logo: "/assets/images/masthead_logo.png"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Personal website
twitter_username: 
github_username: 
minimal_mistakes_skin: contrast
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name             : "Neco Kriel"
  avatar           : "/assets/images/avatar.jpg"
  bio              : "2nd year PhD Student at The Australian National University"
  location         : "ANU, Canberra, Australia"
  email            : 
  links:
    - label: "Email: neco.kriel@anu.edu.au"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:neco.kriel(at)anu.edu.au"
    - label: "OrcID: 0000-0002-3558-3926"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-3558-3926"
    - label: "GitHub: AstroKriel"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/astrokriel"
#    - label: "Google Scholar"
#      icon: "fab fa-fw fa-google-scholar"
#      url: "https://scholar.google.com/citations?hl=en&user=cUAUnsIAAAAJ"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:neco.kriel(at)anu.edu.au"
    - label: "OrcID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-3558-3926"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/astrokriel"
atom_feed:
  hide: true


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
